### ISSUE TITLE
Issue with compatibility with Spike

### ISSUE THREAD

**Issue by Elbone** [mkdecisiondev/reshape-component#2]
This is a borderline support request so apologies in advance.

I'm trying to get this plugin to work with [Spike](www.spike.cf) and having some compatibility issues (or did I miss something?).

I'm using the default Spike project with no changes except in my config:
```
const htmlStandards = require('reshape-standard')
// Component plugin — https://github.com/mkdecisiondev/reshape-component
const includeComponent = require('reshape-component')
const cssStandards = require('spike-css-standards')
const jsStandards = require('spike-js-standards')
const pageId = require('spike-page-id')
const sugarml = require('sugarml')
const sugarss = require('sugarss')
const env = process.env.SPIKE_ENV

module.exports = {
  devtool: 'source-map',
  matchers: { html: '*(**/)*.sgr', css: '*(**/)*.sss' },
  ignore: ['**/layout.sgr', '**/_*', '**/.*', 'readme.md', 'yarn.lock', 'package-lock.json'],
  reshape: htmlStandards({
    parser: sugarml,
    locals: (ctx) => { return { pageId: pageId(ctx), foo: 'bar' } },
    minify: env === 'production'
  }),
  postcss: cssStandards({
    parser: sugarss,
    minify: env === 'production',
    warnForDuplicates: env !== 'production'
  }),
  babel: jsStandards(),
  // https://spike.readme.io/docs/plugins-loaders
  plugins: [
    includeComponent()
  ]
}
```

I have also added the files for the component, and dropped a component tag into the template.

I've tried numerous configs but the main console error I get warns:
`TypeError: Array.prototype.reduce called on null or undefined` in the `when` module.

Seems `when` is used for promise polyfill in Spike core.

Have you tried to use this with Spike? How would you expect it to work?

**Comment by msssk** [comment]
I am using it successfully with Spike, but I'm not using Spike's default template, nor am I using [reshape/standard](https://github.com/reshape/standard).

`reshape-component` is not a webpack loader, it is, just like `reshape-include`, a Reshape plugin.

Looking at the [Reshape docs](https://spike.readme.io/docs/appjs) I suspect the way to load it with the default Spike template would be:

```javascript
// ...
const reshapeComponent = require('reshape-component');

module.exports = {
    // ...
    reshape: {
        appendPlugins: reshapeComponent()
    }
}
```

Relevant source in [`reshape/standard`](https://github.com/reshape/standard/blob/63d2e9b7ba3e87cbb4a91ee9323157349ea69f3d/lib/index.js#L70)

Let me know if this works - I think this will be useful information to include in the docs. Personally, I am loading it [immediately after include](https://github.com/reshape/standard/blob/63d2e9b7ba3e87cbb4a91ee9323157349ea69f3d/lib/index.js#L60), before expressions - I wonder if it is indeed important to load it before expressions or any other plugins.

**Comment by Elbone** [comment]
Ah, yes... of course it's not a loader. 🙄 Hah!

**Comment by Elbone** [comment]
Okay, so for anyone finding this thread the solution is to add the commented code into your config file:
```javascript
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('spike-js-standards')
// Reference reshape-component
const reshapeComponent = require('reshape-component')
const pageId = require('spike-page-id')
const env = process.env.SPIKE_ENV

module.exports = {
  devtool: 'source-map',
  ignore: ['**/layout.html', '**/_*', '**/.*', 'readme.md', 'yarn.lock', 'package-lock.json'],
  reshape: htmlStandards({
    locals: (ctx) => { return { pageId: pageId(ctx), foo: 'bar' } },
    minify: env === 'production',
    // Add this config
    appendPlugins: [
      reshapeComponent()
    ]
  }),
  postcss: cssStandards({
    minify: env === 'production',
    warnForDuplicates: env !== 'production'
  }),
  babel: jsStandards()
}
```
